/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CommandExecution */

#ifndef _Included_CommandExecution
#define _Included_CommandExecution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CommandExecution
 * Method:    exec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CommandExecution_exec
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
